In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("merged_observations.csv", sep=';')
df.head()

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg,Unnamed: 13
0,11:11813,ASBA,BRATISLAVA - KOLIBA,48.167778,17.105833,287.0,2018-01-01T00:00:00Z,0.5,975.5,99.8,0.00,1.9,77.0,NaN
1,11:11816,ASIB,BRATISLAVA - LETISKO,48.170278,17.207500,133.0,2018-01-01T00:00:00Z,1.3,994.7,99.0,0.00,5.6,52.0,NaN
2,11:11819,ASJB,JASLOVSKE BOHUNICE,48.486111,17.663889,174.0,2018-01-01T00:00:00Z,0.4,990.5,98.5,0.00,1.8,50.0,NaN
3,11:11826,ASPP,PIESTANY,48.613056,17.831667,163.0,2018-01-01T00:00:00Z,0.4,991.7,99.0,0.00,1.3,26.0,NaN
4,11:11841,ASZI,ZILINA - DOLNY HRICOV,49.232500,18.614167,309.0,2018-01-01T00:00:00Z,0.5,974.5,99.0,0.00,0.4,247.0,NaN

In [ ]:
df = df.drop(columns=["Unnamed: 13"])
df.head()

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg
0,11:11813,ASBA,BRATISLAVA - KOLIBA,48.167778,17.105833,287.0,2018-01-01T00:00:00Z,0.5,975.5,99.8,0.00,1.9,77.0
1,11:11816,ASIB,BRATISLAVA - LETISKO,48.170278,17.207500,133.0,2018-01-01T00:00:00Z,1.3,994.7,99.0,0.00,5.6,52.0
2,11:11819,ASJB,JASLOVSKE BOHUNICE,48.486111,17.663889,174.0,2018-01-01T00:00:00Z,0.4,990.5,98.5,0.00,1.8,50.0
3,11:11826,ASPP,PIESTANY,48.613056,17.831667,163.0,2018-01-01T00:00:00Z,0.4,991.7,99.0,0.00,1.3,26.0
4,11:11841,ASZI,ZILINA - DOLNY HRICOV,49.232500,18.614167,309.0,2018-01-01T00:00:00Z,0.5,974.5,99.0,0.00,0.4,247.0

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.head()

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg
0,11:11813,ASBA,BRATISLAVA - KOLIBA,48.167778,17.105833,287.0,2018-01-01T00:00:00Z,0.5,975.5,99.8,0.00,1.9,77.0
1,11:11816,ASIB,BRATISLAVA - LETISKO,48.170278,17.207500,133.0,2018-01-01T00:00:00Z,1.3,994.7,99.0,0.00,5.6,52.0
2,11:11819,ASJB,JASLOVSKE BOHUNICE,48.486111,17.663889,174.0,2018-01-01T00:00:00Z,0.4,990.5,98.5,0.00,1.8,50.0
3,11:11826,ASPP,PIESTANY,48.613056,17.831667,163.0,2018-01-01T00:00:00Z,0.4,991.7,99.0,0.00,1.3,26.0
4,11:11841,ASZI,ZILINA - DOLNY HRICOV,49.232500,18.614167,309.0,2018-01-01T00:00:00Z,0.5,974.5,99.0,0.00,0.4,247.0

In [ ]:
df['name'] = (df['name']
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', '_', regex=True)
    .str.replace(r'-+', '_', regex=True)
    .str.replace(r'_+', '_', regex=True)
)
df.head()

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg
0,11:11813,ASBA,bratislava_koliba,48.167778,17.105833,287.0,2018-01-01T00:00:00Z,0.5,975.5,99.8,0.00,1.9,77.0
1,11:11816,ASIB,bratislava_letisko,48.170278,17.207500,133.0,2018-01-01T00:00:00Z,1.3,994.7,99.0,0.00,5.6,52.0
2,11:11819,ASJB,jaslovske_bohunice,48.486111,17.663889,174.0,2018-01-01T00:00:00Z,0.4,990.5,98.5,0.00,1.8,50.0
3,11:11826,ASPP,piestany,48.613056,17.831667,163.0,2018-01-01T00:00:00Z,0.4,991.7,99.0,0.00,1.3,26.0
4,11:11841,ASZI,zilina_dolny_hricov,49.232500,18.614167,309.0,2018-01-01T00:00:00Z,0.5,974.5,99.0,0.00,0.4,247.0

In [ ]:
df['date'] = (df['date']
 .str.replace(r'T.*', '', regex=True)
)
df.head()

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg
0,11:11813,ASBA,bratislava_koliba,48.167778,17.105833,287.0,2018-01-01,0.5,975.5,99.8,0.00,1.9,77.0
1,11:11816,ASIB,bratislava_letisko,48.170278,17.207500,133.0,2018-01-01,1.3,994.7,99.0,0.00,5.6,52.0
2,11:11819,ASJB,jaslovske_bohunice,48.486111,17.663889,174.0,2018-01-01,0.4,990.5,98.5,0.00,1.8,50.0
3,11:11826,ASPP,piestany,48.613056,17.831667,163.0,2018-01-01,0.4,991.7,99.0,0.00,1.3,26.0
4,11:11841,ASZI,zilina_dolny_hricov,49.232500,18.614167,309.0,2018-01-01,0.5,974.5,99.0,0.00,0.4,247.0

In [ ]:
df.to_csv("data.csv", index=False)

In [ ]:
df.name.unique()

array(['bratislava_koliba', 'bratislava_letisko', 'jaslovske_bohunice',
       'piestany', 'zilina_dolny_hricov', 'nitra_velke_janikovce',
       'mochovce', 'hurbanovo', 'prievidza', 'dudince', 'sliac', 'chopok',
       'liesek', 'lucenec_bolkovce', 'lomnicky_stit', 'strbske_pleso',
       'poprad', 'telgart', 'moldava_nad_bodvou', 'presov_vojsko',
       'kojsovska_hola', 'kosice_letisko', 'tisinec', 'milhostov',
       'kamenica_nad_cirochou', 'trencin', 'senica', 'myjava',
       'maly_javornik', 'turzovka', 'liptovsky_mikulas_ondrasova',
       'velke_lovce', 'muzla', 'banska_bystrica_zelena',
       'ziar_nad_hronom', 'banska_stiavnica', 'lom_nad_rimavicou',
       'brezno', 'spisske_vlachy', 'podolinec', 'ganovce', 'bardejov',
       'jakubovany', 'gabcikovo', 'martin_zabokreky',
       'tatranska_javorina', 'stara_lesna', 'krasny_brod',
       'medzilaborce_borov', 'zilina', 'modra_piesok', 'oravska_lesna',
       'ruzomberok', 'moldava_nad'], dtype=object)

In [ ]:
station_mapping = {
    'bratislava_koliba': 'Bratislava - Koliba',
    'bratislava_letisko': 'Bratislava - Letisko',
    'jaslovske_bohunice': 'Jaslovské Bohunice',
    'piestany': 'Piešťany',
    'zilina_dolny_hricov': 'Žilina - Dolný Hričov',
    'nitra_velke_janikovce': 'Nitra - Veľké Janíkovce',
    'mochovce': 'Mochovce',
    'hurbanovo': 'Hurbanovo',
    'prievidza': 'Prievidza',
    'dudince': 'Dudince',
    'sliac': 'Sliač',
    'chopok': 'Chopok',
    'liesek': 'Liesek',
    'lucenec_bolkovce': 'Lučenec - Boľkovce',
    'lomnicky_stit': 'Lomnický Štít',
    'strbske_pleso': 'Štrbské Pleso',
    'poprad': 'Poprad',
    'telgart': 'Telgárt',
    'moldava_nad_bodvou': 'Moldava nad Bodvou',
    'presov_vojsko': 'Prešov - Vojsko',
    'kojsovska_hola': 'Kojšovská Hoľa',
    'kosice_letisko': 'Košice - Letisko',
    'tisinec': 'Tisinec',
    'milhostov': 'Milhostov',
    'kamenica_nad_cirochou': 'Kamenica nad Cirochou',
    'trencin': 'Trenčín',
    'senica': 'Senica',
    'myjava': 'Myjava',
    'maly_javornik': 'Malý Javorník',
    'turzovka': 'Turzovka',
    'liptovsky_mikulas_ondrasova': 'Liptovský Mikuláš - Ondrašová',
    'velke_lovce': 'Veľké Lovce',
    'muzla': 'Mužla',
    'banska_bystrica_zelena': 'Banská Bystrica - Zelená',
    'ziar_nad_hronom': 'Žiar nad Hronom',
    'banska_stiavnica': 'Banská Štiavnica',
    'lom_nad_rimavicou': 'Lom nad Rimavicou',
    'brezno': 'Brezno',
    'spisske_vlachy': 'Spišské Vlachy',
    'podolinec': 'Podolínec',
    'ganovce': 'Gánovce',
    'bardejov': 'Bardejov',
    'jakubovany': 'Jakubovany',
    'gabcikovo': 'Gabčíkovo',
    'martin_zabokreky': 'Martin - Zábrokeky',
    'tatranska_javorina': 'Tatranská Javorina',
    'stara_lesna': 'Stará Lesná',
    'krasny_brod': 'Krásny Brod',
    'medzilaborce_borov': 'Medzilaborce - Borov',
    'zilina': 'Žilina',
    'modra_piesok': 'Modra - Piesok',
    'oravska_lesna': 'Oravská Lesná',
    'ruzomberok': 'Ružomberok',
}

In [ ]:
variables = ["ta_2m", "pa", "rh", "pr_1h", "ws_avg", "wd_avg"]

In [ ]:
station_coordinates = {}
for cccc in df.cccc.unique():
  station_coordinates[cccc] = {
      "lat": df.lat[df.cccc == cccc].unique()[0],
      "lon": df.lon[df.cccc == cccc].unique()[0],
      "elev": df.elev[df.cccc == cccc].unique()[0],
      "name": station_mapping[df.name[df.cccc==cccc].unique()[0]]
  }

In [ ]:
station_coordinates

{'ASBA': {'lat': 48.167778,
  'lon': 17.105833,
  'elev': 287.0,
  'name': 'Bratislava - Koliba'},
 'ASIB': {'lat': 48.170278,
  'lon': 17.2075,
  'elev': 133.0,
  'name': 'Bratislava - Letisko'},
 'ASJB': {'lat': 48.486111,
  'lon': 17.663889,
  'elev': 174.0,
  'name': 'Jaslovské Bohunice'},
 'ASPP': {'lat': 48.613056,
  'lon': 17.831667,
  'elev': 163.0,
  'name': 'Piešťany'},
 'ASZI': {'lat': 49.2325,
  'lon': 18.614167,
  'elev': 309.0,
  'name': 'Žilina - Dolný Hričov'},
 'ASNI': {'lat': 48.280278,
  'lon': 18.133889,
  'elev': 135.0,
  'name': 'Nitra - Veľké Janíkovce'},
 'ASMO': {'lat': 48.288889, 'lon': 18.455, 'elev': 260.0, 'name': 'Mochovce'},
 'ASHU': {'lat': 47.8725,
  'lon': 18.193056,
  'elev': 112.0,
  'name': 'Hurbanovo'},
 'ASPE': {'lat': 48.767594,
  'lon': 18.592987,
  'elev': 260.0,
  'name': 'Prievidza'},
 'ASDU': {'lat': 48.169722,
  'lon': 18.876944,
  'elev': 139.0,
  'name': 'Dudince'},
 'ASSL': {'lat': 48.64167, 'lon': 19.14028, 'elev': 313.0, 'name': 'Sliač'},
 'LZSL': {'lat': 48.639006, 'lon': 19.139493, 'elev': 313.0, 'name': 'Sliač'},
 'ASCH': {'lat': 48.943333,
  'lon': 19.588889,
  'elev': 1995.0,
  'name': 'Chopok'},
 'ASLK': {'lat': 49.369523, 'lon': 19.678204, 'elev': 692.0, 'name': 'Liesek'},
 'ASLU': {'lat': 48.339365,
  'lon': 19.733876,
  'elev': 214.0,
  'name': 'Lučenec - Boľkovce'},
 'ASLS': {'lat': 49.195278,
  'lon': 20.213056,
  'elev': 2634.0,
  'name': 'Lomnický Štít'},
 'ASSP': {'lat': 49.117785,
  'lon': 20.062418,
  'elev': 1319.0,
  'name': 'Štrbské Pleso'},
 'ASTT': {'lat': 49.068056, 'lon': 20.249444, 'elev': 694.0, 'name': 'Poprad'},
 'ASTG': {'lat': 48.848362,
  'lon': 20.187658,
  'elev': 906.0,
  'name': 'Telgárt'},
 'ASMB': {'lat': 48.615076,
  'lon': 21.005117,
  'elev': 215.0,
  'name': 'Moldava nad Bodvou'},
 'LZPW': {'lat': 49.03,
  'lon': 21.304444,
  'elev': 308.0,
  'name': 'Prešov - Vojsko'},
 'ASKH': {'lat': 48.782907,
  'lon': 20.987029,
  'elev': 1247.0,
  'name': 'Kojšovská Hoľa'},
 'ASKZ': {'lat': 48.670761,
  'lon': 21.238661,
  'elev': 230.0,
  'name': 'Košice - Letisko'},
 'ASSK': {'lat': 49.214722,
  'lon': 21.646389,
  'elev': 216.0,
  'name': 'Tisinec'},
 'ASMI': {'lat': 48.663056,
  'lon': 21.721944,
  'elev': 103.0,
  'name': 'Milhostov'},
 'ASKC': {'lat': 48.934722,
  'lon': 21.994444,
  'elev': 175.0,
  'name': 'Kamenica nad Cirochou'},
 'ASTN': {'lat': 48.866389,
  'lon': 17.999444,
  'elev': 204.0,
  'name': 'Trenčín'},
 'ASSE': {'lat': 48.68915, 'lon': 17.403094, 'elev': 231.0, 'name': 'Senica'},
 'ASMY': {'lat': 48.753333, 'lon': 17.560278, 'elev': 345.0, 'name': 'Myjava'},
 'ASMJ': {'lat': 48.255743,
  'lon': 17.152589,
  'elev': 581.0,
  'name': 'Malý Javorník'},
 'ASTU': {'lat': 49.401564,
  'lon': 18.626783,
  'elev': 496.0,
  'name': 'Turzovka'},
 'ASLM': {'lat': 49.09739,
  'lon': 19.590288,
  'elev': 569.0,
  'name': 'Liptovský Mikuláš - Ondrašová'},
 'ASVL': {'lat': 48.056087,
  'lon': 18.335425,
  'elev': 186.0,
  'name': 'Veľké Lovce'},
 'ASMU': {'lat': 47.800456, 'lon': 18.595672, 'elev': 120.0, 'name': 'Mužla'},
 'ASBB': {'lat': 48.733419,
  'lon': 19.115097,
  'elev': 429.0,
  'name': 'Banská Bystrica - Zelená'},
 'ASZR': {'lat': 48.585719,
  'lon': 18.850353,
  'elev': 262.0,
  'name': 'Žiar nad Hronom'},
 'ASBS': {'lat': 48.449061,
  'lon': 18.919689,
  'elev': 570.0,
  'name': 'Banská Štiavnica'},
 'ASLR': {'lat': 48.643889,
  'lon': 19.649167,
  'elev': 1017.0,
  'name': 'Lom nad Rimavicou'},
 'ASBR': {'lat': 48.800347, 'lon': 19.636517, 'elev': 488.0, 'name': 'Brezno'},
 'ASSW': {'lat': 48.944197,
  'lon': 20.80201,
  'elev': 381.0,
  'name': 'Spišské Vlachy'},
 'ASPO': {'lat': 49.262067,
  'lon': 20.542689,
  'elev': 567.0,
  'name': 'Podolínec'},
 'ASGN': {'lat': 49.034741,
  'lon': 20.323284,
  'elev': 703.0,
  'name': 'Gánovce'},
 'ASBJ': {'lat': 49.285045,
  'lon': 21.270903,
  'elev': 311.0,
  'name': 'Bardejov'},
 'ASJK': {'lat': 49.108359,
  'lon': 21.139323,
  'elev': 409.0,
  'name': 'Jakubovany'},
 'ASGB': {'lat': 47.897736,
  'lon': 17.566213,
  'elev': 114.0,
  'name': 'Gabčíkovo'},
 'ASZY': {'lat': 49.026686,
  'lon': 18.922836,
  'elev': 427.0,
  'name': 'Martin - Zábrokeky'},
 'ASTJ': {'lat': 49.263889,
  'lon': 20.139444,
  'elev': 1017.0,
  'name': 'Tatranská Javorina'},
 'ASST': {'lat': 49.15139,
  'lon': 20.289443,
  'elev': 808.0,
  'name': 'Stará Lesná'},
 'ASKB': {'lat': 49.25306,
  'lon': 21.91194,
  'elev': 305.0,
  'name': 'Krásny Brod'},
 'ASBV': {'lat': 49.301648,
  'lon': 21.884013,
  'elev': 349.0,
  'name': 'Medzilaborce - Borov'},
 'ASZA': {'lat': 49.211439, 'lon': 18.771139, 'elev': 358.0, 'name': 'Žilina'},
 'ASMP': {'lat': 48.372778,
  'lon': 17.273889,
  'elev': 533.0,
  'name': 'Modra - Piesok'},
 'ASOL': {'lat': 49.367867,
  'lon': 19.182453,
  'elev': 781.0,
  'name': 'Oravská Lesná'},
 'ASRK': {'lat': 49.071728,
  'lon': 19.34087,
  'elev': 507.0,
  'name': 'Ružomberok'}}

# Chechking weird values

In [ ]:
def try_parse(n):
  try:
    return float(n)
  except:
    return 0 #-inf would make nsmallest useless

for var in variables:
  parsed_series = df[var].apply(try_parse)
  print(var.upper() + "\n")
  print("MAX")
  print(parsed_series.nlargest(5))
  print("MIN")
  print(parsed_series.nsmallest(5))
  print()

TA_2M

MAX
38725    28.0
84513    28.0
38768    27.4
38721    27.2
38726    27.1
Name: ta_2m, dtype: float64
MIN
54987    -27.8
50451    -24.1
802      -23.0
99898    -23.0
100239   -23.0
Name: ta_2m, dtype: float64

PA

MAX
44249    1067.5
90835    1032.6
90852    1032.6
90872    1032.2
87180    1030.6
Name: pa, dtype: float64
MIN
11    0.0
12    0.0
15    0.0
19    0.0
20    0.0
Name: pa, dtype: float64

RH

MAX
103908    14512.8
91650     14347.9
57954       105.0
74370       103.0
101640      103.0
Name: rh, dtype: float64
MIN
92045   -0.3
11       0.0
12       0.0
15       0.0
20       0.0
Name: rh, dtype: float64

PR_1H

MAX
60361     1058.13
64897      526.47
106452      36.30
38504       25.49
61716       21.05
Name: pr_1h, dtype: float64
MIN
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: pr_1h, dtype: float64

WS_AVG

MAX
92045     304.0
96870      64.0
118056     28.4
28848      28.2
23394      28.1
Name: ws_avg, dtype: float64
MIN
11    0.0
12    0.0
15    0.0
20    0.0
49    0.0
Name: ws_avg, dtype: float64

WD_AVG

MAX
2989     360.0
9009     360.0
10861    360.0
12340    360.0
17363    360.0
Name: wd_avg, dtype: float64
MIN
11    0.0
12    0.0
15    0.0
20    0.0
49    0.0
Name: wd_avg, dtype: float64

In [ ]:
df[df.rh == df.max(axis=0).rh]

,obs_stn,cccc,name,lat,lon,elev,date,ta_2m,pa,rh,pr_1h,ws_avg,wd_avg
103908,11:11916,ASCH,chopok,48.943333,19.588889,1995.0,2024-11-23,-12.6,783.3,14512.8,null,11.8,314.2

In [ ]:
df[df.name == "chopok"].rh.apply(try_parse).nlargest(10)

103908    14512.8
91650     14347.9
57954       105.0
74370       103.0
101640      103.0
107958      103.0
123672      103.0
19614       102.0
73668       102.0
94404       102.0
Name: rh, dtype: float64

In [ ]:
df.pr_1h.apply(try_parse).nlargest()

60361     1058.13
64897      526.47
106452      36.30
38504       25.49
61716       21.05
Name: pr_1h, dtype: float64

We will make all weird values null

In [ ]:
def parse(n, var):
  try:
    parsed_val = float(n)
    match var:
      case "ta_2m":
        return parsed_val if -50 <= parsed_val <= 50 else "null"
      case "pa":
        return parsed_val if 750 <= parsed_val <= 1080 else "null"
      case "rh":
        return parsed_val if 0 <= parsed_val <= 120 else "null"
      case "pr_1h":
        return parsed_val if 0 <= parsed_val <= 500 else "null" #no news about extreme rainfall in Jakubovany
      case "ws_avg":
        return parsed_val if 0 <= parsed_val <= 300 else "null" #no news about extreme wind in Javorniky
      case "wd_avg":
        return parsed_val if 0 <= parsed_val <= 360 else "null" #no other possible values
  except:
    return "null"

In [ ]:
dataframes = {}
for var in variables:
    df_var = df.pivot(index="date", columns="cccc", values=var)
    df_var = df_var.map(lambda n: parse(n, var))
    dataframes[var] = df_var

In [ ]:
import shutil
for var, dataframe in dataframes.items():
    dataframe.to_csv(f"output/{var}_data.csv")

shutil.make_archive("data", 'zip', "output")

'/content/data.zip'

In [ ]:
dataframe.head(), var

(cccc         ASBA   ASBB   ASBJ   ASBR   ASBS  ASBV  ASCH   ASDU   ASGB  \
 date
 2018-01-01   77.0  343.3  121.3  118.6   58.5  null  null   51.0  117.2
 2018-01-02   26.3  344.4    4.7  127.6   35.4  null  null    4.0    8.8
 2018-01-03  275.6  321.6  340.7  174.2   25.3  null  null  276.0  302.7
 2018-01-04  261.9  329.5   62.1   93.7  255.0  null  null  130.0  204.0
 2018-01-05   81.9   58.4  184.6   46.0  230.2  null  null  105.0  184.7

 cccc         ASGN  ...   ASTN   ASTT   ASTU   ASVL   ASZA   ASZI   ASZR  \
 date               ...
 2018-01-01  150.0  ...   27.5  143.0  321.5   86.7  160.7  247.0  296.1
 2018-01-02  297.0  ...  100.8  128.0  270.2  264.6  172.8  107.0   69.6
 2018-01-03  296.0  ...  304.1  250.0  250.9  275.7  144.2  238.0  345.5
 2018-01-04  149.0  ...  246.7  250.0  234.5  196.1  308.5  289.0  358.2
 2018-01-05  177.0  ...  162.0  189.0  227.0  101.4  219.1  245.0   87.7

 cccc         ASZY  LZPW  LZSL
 date
 2018-01-01  184.6  null  null
 2018-01-02  325.9  null  null
 2018-01-03  217.4  null  null
 2018-01-04  189.2  null  null
 2018-01-05  239.8  null  null

 [5 rows x 54 columns],
 'wd_avg')

In [ ]:
dataframes["pr_1h"].map(try_parse).max()

cccc
ASBA    17.30
ASBB    15.42
ASBJ    10.29
ASBR     6.56
ASBS    15.68
ASBV     8.63
ASCH     0.00
ASDU    12.40
ASGB    12.52
ASGN     9.80
ASHU     9.81
ASIB     6.70
ASJB    25.49
ASJK     7.37
ASKB    21.05
ASKC     6.10
ASKH    20.73
ASKZ    15.70
ASLK    10.80
ASLM    15.74
ASLR     8.72
ASLS     0.00
ASLU    12.79
ASMB    10.59
ASMI    14.84
ASMJ    15.89
ASMO    17.70
ASMP     8.05
ASMU     7.27
ASMY    10.14
ASNI    10.32
ASOL    11.08
ASPE    10.88
ASPO    18.54
ASPP    13.40
ASRK    20.91
ASSE     8.52
ASSK    12.20
ASSL    11.20
ASSP    10.15
ASST    10.30
ASSW    18.14
ASTG    36.30
ASTJ    10.06
ASTN    15.19
ASTT    11.40
ASTU    10.52
ASVL     7.89
ASZA     8.97
ASZI     8.60
ASZR    15.74
ASZY    12.57
LZPW     0.40
LZSL    11.30
dtype: float64